### PR TITLE
Changing the encoding from windows to UTF-8

### PR DESCRIPTION
**Pull request by ulysse314**
Hello,

I would like to suggest to move to UTF-8. It is a bit more generic for all platform. I have no problem if you prefer to refuse my pull request :).

thanks

### CODE REVIEW

**Review by flav1972 — APPROVED** [review]

**Comment by ulysse314** [comment]
Thinking about it, I'm not even sure why we need non-ASCII characters...

**Comment by flav1972** [comment]
Me neither. Aller text is ascii

Le jeu. 14 févr. 2019 à 09:06, ulysse314 <notifications@github.com> a
écrit :

**Comment by ulysse314** [comment]
Let me update this pull request... Thanks.

**Comment by ulysse314** [comment]
Done

**Comment by ulysse314** [comment]
The "–" is not an ascii character. This is not "-".

**Comment by flav1972** [comment]
Reading this on my phone.
I haven't seen that it is a "long minus ". We can use the normal one. The
second in your message.

Le ven. 15 févr. 2019 à 02:35, ulysse314 <notifications@github.com> a
écrit :

**Review by flav1972 — APPROVED** [review]

**Pull request merged**
